module.exports = {
  ADD_RECIPE: 'ADD_RECIPE',
  EDIT_RECIPE: 'EDIT_RECIPE',
  DELETE_RECIPE: 'DELETE_RECIPE',
  ADD_INGREDIENT: 'ADD_INGREDIENT',
  EDIT_INGREDIENT: 'EDIT_INGREDIENT',
  DELETE_INGREDIENT: 'DELETE_INGREDIENT'
}
